made the SignUp and the LoginPage Ui
algovengers/Hairify pull request #73
Opened 2024-05-12 07:09 UTC by SumitKumar-17

The Sign Up Page and the Login page have been corrected and they are updated with the deign as per the Homepage

2024-05-12 08:22 UTC, afeefuddin commented
LGTM, overall but can you tweak the color of the signup and login button a bit. Do upload screenshots before asking for review.

2024-05-12 09:05 UTC, SumitKumar-17 commented
![test1](https://github.com/algovengers/Hairify/assets/118801141/d93e5905-dfa2-44d6-a0d4-8f9438623e3a)
Do you like this color of the Button?

2024-05-12 09:33 UTC, afeefuddin commented
Okh, so color is not our priority that much currently so maybe you can skip that part for now but one issue which you should fix is the border which is visible when we are selecting the input box.
Otherwise LGTM.
![Screenshot (76)](https://github.com/algovengers/Hairify/assets/126336384/77daa4f7-3e57-4e17-9449-11c54ed9f1eb)

2024-05-12 12:28 UTC, SumitKumar-17 commented
![test45](https://github.com/algovengers/Hairify/assets/118801141/f19c0606-9ef7-42b0-b441-3a071b9ff622)

2024-05-12 13:07 UTC, afeefuddin commented
Okh, you can push this and squash both the commits.

2024-05-12 14:15 UTC, SumitKumar-17 commented
@afeefuddin  I have completed it and squashed my commit into a single one.

2024-05-13 09:27 UTC, afeefuddin requested changes

2024-05-13 09:27 UTC, afeefuddin commented on frontend/src/app/login/page.tsx
> +                onClick={handleLogin}
Since you have added the type submit here you need to add `e.preventDefault` in `handleLogin` function in order to avoid refreshing the page.

2024-05-13 09:27 UTC, afeefuddin commented on frontend/src/app/signup/page.tsx
> +                onClick={handleSignup}
Same here

2024-05-13 14:46 UTC, SumitKumar-17 commented
@afeefuddin  added the e.preventDefault() int he handleLogin and handleSignup function.

2024-05-13 17:05 UTC, afeefuddin commented
where have you added `e.preventDefault`? I don't see it, plus you have messed up the typescript there.

2024-05-13 17:23 UTC, SumitKumar-17 commented
@afeefuddin  Oh i got that .Actually some error happened I think while I was squashing my commits  and the e.preventDefault() got erased. Please have a look into it now.

2024-05-15 12:27 UTC, afeefuddin commented
LGTM. One final thing, you should update the Image in the readme file (do it in a separate commit in this PR).

2024-05-15 12:28 UTC, afeefuddin approved these changes

2024-05-16 16:31 UTC, SumitKumar-17 commented
@afeefuddin  
Hi i have a doubt about readme file . 
So basically like i was proceeding by creating a assets folder and then I would add the images to the readme form there.

But when I saw your previous code you were making the readme images from another repository of your gtihub account . Like the Login image is present from another repository named as Mindmate.
![signup](https://github.com/algovengers/Hairify/assets/118801141/c426252b-da11-4312-b974-36bbac24e676)

2024-05-16 16:32 UTC, SumitKumar-17 commented
So shoud i proceed with the assets folder above?

2024-05-16 16:39 UTC, SumitKumar-17 commented
@afeefuddin  like I cannot directly uplate readme from my side because it will contain my github username if you make a merge request.

So that why I need to make a separate assets folder for it .

2024-05-16 20:01 UTC, afeefuddin commented
No worries, I'll update that.

2024-05-16 20:01 UTC, merged

2024-05-16 20:02 UTC, afeefuddin commented
Merged @SumitKumar-17. Thanks for doing this.